### ISSUE TITLE
GTSRB dataset 

### ISSUE THREAD

**Issue by suryatejaCH** [mahyarnajibi/fast-rcnn-torch#10]
My Btech project is using Fast RCNN on GTSRB dataset to detect traffic signs but the annotations are in .txt file. Can you tell how to use this method for my dataset

**Comment by mahyarnajibi** [comment]
For this, a new class can be implemented in the dataset folder which inherits from the DataSetDetection class and defines its virtual functions i.e. getGTBoxes(idx), getROIBoxes(idx) etc (e.g. take a look at DataSetPascal or DataSetCoco as an example). In this case, you may need to parse the text file and return the appropriate ground-truth boxes (in [x1 y1 x2 y2] format) from these functions 
Once you implemented the new dataset class, you can register it in the detection.lua file and use it in the main_test.lua and main_train.lua scripts.
