### ISSUE TITLE
run demo.lua fail

### ISSUE THREAD

**Issue by superwj1990** [mahyarnajibi/fast-rcnn-torch#11]
when I run the qlua demo.lua, it says:
Unable to connect X11 server (continuing with -nographics)
THCudaCheck FAIL file=/home/wangjian/torch/extra/cutorch/init.c line=255 error=2 : out of memory
qlua: /home/wangjian/torch/install/share/lua/5.1/cudnn/find.lua:192: cuda runtime error (2) : out of memory at /home/wangjian/torch/extra/cutorch/init.c:255
stack traceback:
	[C]: at 0x7f8da3db19c0
	[C]: in function 'synchronizeAll'
	/home/wangjian/torch/install/share/lua/5.1/cudnn/find.lua:192: in function 'reset'
	/home/wangjian/torch/install/share/lua/5.1/cudnn/find.lua:554: in main chunk
	[C]: in function 'require'
	/home/wangjian/torch/install/share/lua/5.1/cudnn/init.lua:319: in main chunk
	[C]: in function 'require'
	./detection.lua:2: in main chunk
	[C]: in function 'require'
	demo.lua:3: in main chunk

**Comment by mahyarnajibi** [comment]
The demo.lua needs a graphical display only to show the detections graphically. It seems that no graphical displays were defined in the runtime environment. Did you run the code on a remote server? (It might be the case that you used ssh to connect to your remote server and forgot the -X option to set the X11 forwarding).
