### ISSUE TITLE
Proposals file not found

### ISSUE THREAD

**Issue by serhangul** [mahyarnajibi/fast-rcnn-torch#13]
Hi, when I run `./scripts/get_proposals.sh` I get an Error 404: Not found. It looks like the link [https://people.eecs.berkeley.edu/~rbg/fast-rcnn-data/selective_search_data.tgz](https://people.eecs.berkeley.edu/~rbg/fast-rcnn-data/selective_search_data.tgz)
 is dead. Is there any other source?

**Comment by mahyarnajibi** [comment]
Hi,
I uploaded the file and updated the link. You should be able to download it now.

**Comment by serhangul** [comment]
Thanks, but I still cannot download it. Is the above link working for you?

**Comment by mahyarnajibi** [comment]
Sure, did you pull the latest commit? I updated the link in scripts/get_proposals.sh (commit 8a6f1c3). The data should be accessible here: http://www.umiacs.umd.edu/~najibi/data/selective_search_data.tar.gz

**Comment by serhangul** [comment]
Thank you, somehow I still had the old version... Now I pulled the new one and the problem is solved.
