### ISSUE TITLE
MAP (means average precision)calculation Code

### ISSUE THREAD

**Issue by vinodkkurmi** [mahyarnajibi/fast-rcnn-torch#14]
Hi , 
Can anyone tell where is the means average precision in the code???
thanks

**Comment by naritapandhe** [comment]
PASCAL VOC development kit comes with the evaluation code which exists in the VOCcode folder. It consists of functions such as VOCevaldet, VOCevalcls to evaluate the prediction results. You can find its documentation over here: [VOC 2007 Development Kit](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/htmldoc/index.html)
The fast-rcnn-torch code invokes VOCevaldet(which calculates the mAP) from its wrappers which are in [https://github.com/mahyarnajibi/fast-rcnn-torch/tree/master/utils/VOCdevkit-matlab-wrapper](https://github.com/mahyarnajibi/fast-rcnn-torch/tree/master/utils/VOCdevkit-matlab-wrapper)

**Comment by vinodkkurmi** [comment]
@naritapandhe  Thanks Narita
