### ISSUE TITLE
ERROR in ./scripts

### ISSUE THREAD

**Issue by capuzz** [mahyarnajibi/fast-rcnn-torch#17]
Hi,
I'm trying to download the the pre-trained model and object proposal from the _/script_ folder but the links in _get_imgnet_models.sh, get_proposals.sh_ and _get_frcnn_models_ are not available. 
Then I tried to open the links from browser but of course they don't work (ERROR 403: Forbidden).

Are there other links to download that files?
Thanks

**Comment by mahyarnajibi** [comment]
Hi,
Sorry, it was a server configuration problem, now you should be able to download the files.
