### ISSUE TITLE
The VGG Pre-trained model

### ISSUE THREAD

**Issue by wlw208dzy** [mahyarnajibi/fast-rcnn-torch#5]
Thanks for releasing the Fast-RCNN code based on torch. I would like to train a new detection model from VGG pre-trained one. But I noticed that you have only published Alex pre-trained model for now. Would you mind to share **VGG pre-trained model**? Thank you very much!

**Comment by mahyarnajibi** [comment]
You can download the VGG16 imagenet pre-trained file by running scripts/get_imgnet_models.sh . Also you can convert any caffemodel file to a torch file (See utils/main_caffe_convert.lua).
