### ISSUE TITLE
qlua: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by hbzhang** [mahyarnajibi/fast-rcnn-torch#9]
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-2572/cutorch/lib/THC/THCTensorRandom.cu line=20 error=2 : out of memory
qlua: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-2572/cutorch/lib/THC/THCTensorRandom.cu:20
stack traceback:
    [C]: at 0x010a734870
    [C]: at 0x1739c460
    [C]: in function 'require'
    /Users/hbzhang/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk
    [C]: in function 'require'
    /Users/hbzhang/torch/install/share/lua/5.1/cudnn/init.lua:1: in main chunk
    [C]: in function 'require'
    ./detection.lua:2: in main chunk
    [C]: in function 'require'
    demo.lua:3: in main chunk

Get this error. How I can fix it? Thank you!

**Comment by mahyarnajibi** [comment]
This seems to be a  cudnn installation problem. Did you check whether you can use cudnn in the torch environment after installation? As an example can you run **require 'cudnn'** in a th environment?

**Comment by hbzhang** [comment]
The require 'cudnn' works fine.... My GPU 750m has 2GB memory. Thanks!
